name: Deploy to VPS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add VPS to known_hosts
      run: |
        mkdir -p ~/.ssh
        echo "|1|ZjeV5t6cCAa2Q+eeeG5Z8Pnbkw4=|qXChzs19SAnhQK6mcPw/GGZgZBQ= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDrnk+AcBXZlmyFKur29CQWZLkTSpiSbZ7GUSxJf6yl1v7LTPznMRrNixlOP7axgVTHjuDrC5VslKiNA2sceCBv8h3gHl9s/8eV0oUDRR9hASVIBEeJeLq/9cpaRRjFR964uyVl+6crUGm524vlBNOqVAaE5u7SSb5jQ7jI+R+1fAXKmRgIruyvZybk4cohI4pX0iQJ36yf9rssikaB/ud+LIigzxNiXAWe2VjuI/2QfNxZwbPdqoJ7tjqsQikOJcq8ERm/nLPTkFg/W3rq/78Dk3azznBupBNl4wkdVvyW6upQ5ihRJLUN8ysQ+T2l3V09yS7IfuwSzWYS5sXMvLsC1azOTJoOfQrH/BWqG58IpFkwNm/1uMpmPtXDyaUH2GctCEHucIy4ByRt2hZxxLJ5yw91C/ob3sUf8VbuvVTm4ES6I0qS5T25voRw/Bu6Esgf7EbHhpxptDuO0LN67ZCAUqRP9dFR9D0d0/592zy0Rj/NO4Pyb/QWCnG02gcueM0=" >> ~/.ssh/known_hosts
        echo "|1|V8ZAq2g7vaHD2AMTCdXZw7wX8a0=|YNOvuroL+8y0qHt8YmyKcqHMDb8= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKnLnBklcGs6IAxpVekf1+TgKPCjb27Bu1s7wK9TMHiWie2Js/pp6uKXAuhG9mK1YqVmaCrDHXaKqQULyda+Etg=" >> ~/.ssh/known_hosts
        echo "|1|kzEnraao/vimqvIiofEfhaPEk4A=|jbGiNBqcfxFAuVijXZMKfCUmr5w= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFQPuaTc6jmy1yWT76me5c9X/mGapoU1n6vlqiOHGJeX" >> ~/.ssh/known_hosts

    - name: Copy files via SSH
      run: scp -r ./* root@213.210.21.113:/var/www/vanilla-portfolio-website

    - name: SSH and deploy
      run: ssh root@213.210.21.113 'cd /var/www/vanilla-portfolio-website && docker-compose down && docker-compose up -d --build'
